name: VEVOR Weather Station Bridge (Go)
version: 0.1.5
slug: vevor-weatherbridge-go
description: >-
  Intercepts VEVOR weather station data and forwards it to Home Assistant via
  MQTT (Go implementation)
url: https://github.com/lenucksi/VevorWeatherbridge
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
  - i386
startup: application
boot: auto
init: false
hassio_api: true
services:
  - mqtt:need
ports:
  80/tcp: 8098
ports_description:
  80/tcp: Weather station HTTP endpoint (default 8098, can be changed)
map:
  - config:rw
options:
  device_name: Weather Station
  device_manufacturer: VEVOR
  device_model: 7-in-1 Weather Station
  units: metric
  mqtt_host: ''
  mqtt_port: 1883
  mqtt_user: ''
  mqtt_password: ''
  mqtt_prefix: homeassistant
  timezone: Europe/Berlin
  wu_forward: false
  wu_username: ''
  wu_password: ''
  log_level: INFO
schema:
  device_name: str
  device_manufacturer: str
  device_model: str
  units: list(metric|imperial)
  mqtt_host: str?
  mqtt_port: port
  mqtt_user: str?
  mqtt_password: password?
  mqtt_prefix: str
  timezone: str
  wu_forward: bool
  wu_username: str?
  wu_password: password?
  log_level: list(DEBUG|INFO|WARNING|ERROR)
image: ghcr.io/lenucksi/vevor-weatherbridge-go-{arch}
